"""Initial migration after cleaning up database

Revision ID: 14843191f503
Revises: 
Create Date: 2024-12-28 02:02:48.356100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14843191f503'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_clinic')
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_patient_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint('fk_patient_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    op.create_table('_alembic_tmp_clinic',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('contact', sa.VARCHAR(length=150), nullable=False),
    sa.Column('head_doctor', sa.VARCHAR(length=150), nullable=False),
    sa.Column('address', sa.VARCHAR(length=150), nullable=False),
    sa.Column('photo', sa.VARCHAR(length=150), nullable=True),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='fk_clinic_user'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
